### ISSUE TITLE
[v0.6.0] Release Tracker

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#1025]
### 🚀 The feature

We cut a [release branch](https://github.com/pytorch/data/tree/release/0.6) for the 0.6.0 release at the same time with PyTorch 2.0.0.

## Cherry-pick (until 2/27/2023)
We will keep cherry-picking all PRs landed to main branch until PyTorch 2.0.0 official released.
When you add PR against release branch, please link the landed PR from main branch.

RC-release can be found in https://download.pytorch.org/whl/test/cpu/torch_test.html or conda: https://anaconda.org/pytorch-test/torchdata

### Motivation, pitch

Tracker for cherry-picking PRs to release branch

- [x] https://github.com/pytorch/data/pull/1014
    - Cherry-pick: #1035 
- [x] https://github.com/pytorch/data/pull/1034
    - Cherry-pick: #1037
- [x] https://github.com/pytorch/data/pull/1036
    - Cherry-pick: #1038
- [x] https://github.com/pytorch/data/pull/1046
    - Cherry-pick: https://github.com/pytorch/data/pull/1049 
- ~~https://github.com/pytorch/data/pull/1044~~
    - Cherry-pick: Will NOT cherry-pick ~~unless https://github.com/pytorch/data/pull/1055 is merged to main~~
- [x] https://github.com/pytorch/data/pull/1050
    - Cherry-pick: #1057
- [x] https://github.com/pytorch/data/pull/1042
    - Cherry-pick: #1057
- [x] https://github.com/pytorch/data/pull/1011
    - Cherry-pick: #1057
- [x] https://github.com/pytorch/data/pull/1041
    - Cherry-pick: #1060
- [x] https://github.com/pytorch/data/pull/1051
    - Cherry-pick: #1057 (PyTorch 2.0 has been updated to C++17)
- [x] https://github.com/pytorch/data/pull/1053
    - Cherry-pick: #1057
