### ISSUE TITLE
Documentation Improvements Tracker

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#195]
Here are some improvements that we should make to the documentation. Some of these likely should be completed before beta release.

- [ ] Add docstrings for the class `IterDataPipe` and `MapDataPipe`
- [ ] Review the categorization of `IterDataPipe` in `torchdata.datapipes.iter.rst`
- [ ] Edit first sentence of each DataPipe docstring to be a concise summary of functionality (also include functional name when it exists)
- [ ] Add tutorial (details TBD)
- [ ] Add domain usage examples

cc: @VitalyFedyunin @ejguan @wenleix @dongreenberg @NivekT

**Comment by linminhtoo** [comment]
Hello, does this issue also plan to update the PyTorch documentation as well? 
Actually, I find it can be quite confusing to first-time users of `datapipes`. 

For example, in the official PyTorch repo, like, https://github.com/pytorch/pytorch/blob/master/torch/utils/data/datapipes/datapipe.py
the doc-string for how to properly multiprocess with `IterDataPipe` is incorrect (bcos the `worker_init_fn` for `IterableDataset` will not work for `IterDataPipe`) and incomplete (bcos it doesn't have the updated documentation about using `.sharding_filter()` and the new `worker_init_fn` that does `.graph_settings.apply_sharding(...)`

**Comment by linminhtoo** [comment]
That being said, I would be happy to contribute, if you could give me pointers on how I can do so.

**Comment by NivekT** [comment]
Hi @linminhtoo,

Thanks for looking into this!

> Hello, does this issue also plan to update the PyTorch documentation as well? it may be slightly confusing to first-time users of `datapipes`, as the documentation in `torchdata` and `torch` can conflict.

This issue does cover our documentation within `torch` as well.

> For example, in the official PyTorch repo, like, https://github.com/pytorch/pytorch/blob/master/torch/utils/data/datapipes/datapipe.py the doc-string for how to properly multiprocess with `IterDataPipe` is:
> 
> * incorrect (bcos the `worker_init_fn` for `IterableDataset` will not work for `IterDataPipe`)

Can you elaborate on that point?

> * incomplete (bcos it doesn't have the updated documentation about using `.sharding_filter()` and the new `worker_init_fn` that does `graph_settings.apply_sharding(...)`)

We are planning to land this PR, after which, users should not need to pass in additional `worker_init_fn` for the purpose of sharding.
* https://github.com/pytorch/pytorch/pull/78631
