### ISSUE TITLE
Tracker of Releng

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#253]
### 🚀 The feature

This issue is used to track TODOs in my mind for releng:
- [x] Compare released git_version with the commit on the top of branch
- [ ] Auto doc gen for RC release
- [ ] Add conda upload
- [ ] Turn on nightly release
- [ ] Turn on nightly doc (currently used main branch )
...

After compilation matrix is enabled:
- [ ] Turn on matrix
- [ ] Add artifacts upload and download. The wheels can be sent to a single job and uploaded at one time. (https://github.com/actions/upload-artifact, https://github.com/actions/download-artifact)
- [ ] Make build workflow as the dependent job for test/doc_gen using `needs`

Others:
- [ ] Add cache

### Motivation, pitch

Improvement for releng

**Comment by NivekT** [comment]
"Auto doc gen for RC release" - I believe we can add a GH action for that (i.e. whenever a push is made to the branch `release/0.x.0`, build a doc in the folder `0.x.0` in the `gh-pages` branch.

**Comment by ejguan** [comment]
> "Auto doc gen for RC release" - I believe we can add a GH action for that (i.e. whenever a push is made to the branch release/0.x.0, build a doc in the folder 0.x.0 in the gh-pages branch.

I am working on it currently. It should be attached after the `build_test_upload` workflow for RC release.

**Comment by ejguan** [comment]
Nightly release is working for wheel. But, it seems the conda token we have used to upload packages to `pytorch` channel cannot be used to upload them to `pytorch-nightly` channel. 
See: https://github.com/pytorch/data/runs/5653050846?check_suite_focus=true

**Comment by ejguan** [comment]
Another bug for wheel, the nightly version currently relies on date https://github.com/pytorch/data/blob/76733df6a8903bf95b938cf611355f05f5c2f821/packaging/pkg_helpers.bash#L93

But, the date on CI macos machine is not correct. I need to do a quick test.
