### ISSUE TITLE
Tracker for Debuggability Improvement

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#284]
### 🚀 The feature

This is a tracker issue for the improvement for debuggability
- [ ] Print out a graph of DataPipe from the Dictionary returned from `traverse` function https://github.com/pytorch/pytorch/blob/11231b0f935c092598c994a4bab686485aac1856/torch/utils/data/graph.py#L54
```mermaid
graph TD;
DP1-->DP2;
DP2-->DP3;
DP2-->DP4;
DP3-->DP5;
DP4-->DP6;
DP5-->DP6;
DP6-->output;
```
can be printed out as the following
```python
>>> print_graph(traverse(dp6))
DP1 -> DP2 -> DP3 -> DP5
         \             \
         DP4 --------> DP6 ->
```
- Find a way to differentiate DataPipe instance in the graph
  - [ ] Provide shorter name for each DataPipe instance.
  - [ ] Provide unique name using incremental number for the instance of the same DataPipe class
- Improve back tracing
  - [ ] During Iteration, remove this profiling part within back tracing https://github.com/pytorch/pytorch/blob/11231b0f935c092598c994a4bab686485aac1856/torch/utils/data/_typing.py#L340
  - [ ] Find the culprit DataPipe for `__len__`.

### Motivation, pitch

This would help our users and developers to easily understand what's going on with the pipeline.
Feel free to post more request for debuggability.

**Comment by NivekT** [comment]
I made a similar [Google Doc](https://docs.google.com/document/d/1-YpeRiRFI7H2RcOyEMJWrKTQ3y6M8bPI7USj_YGkj70/edit#) here. Not sure if it is easier to brainstorm using GitHub issue or the doc to flesh out what we want to do for each point.

**Comment by ejguan** [comment]
We should keep design in google doc. Adding it here for OSS users to gather their feedback

**Comment by pmeier** [comment]
Regarding graph visualization: I needed this today and hacked something together:

```py
from __future__ import annotations

import dataclasses
from typing import Optional, Any

import matplotlib.pyplot as plt
import networkx as nx
from torch.utils.data.graph import traverse


@dataclasses.dataclass(repr=False)
class Node:
    obj: Any
    child: Optional[Node] = None

    def __repr__(self):
        return type(self.obj).__name__

    def __hash__(self):
        return hash(self.obj)


def scan(graph, child=None):
    for node, parents in graph.items():
        current = Node(node, child)
        yield current
        yield from scan(parents, child=current)


def visualize_graph(dp):
    G = nx.DiGraph()
    for node in set(scan(traverse(dp))):
        if node.child is not None:
            G.add_edge(node, node.child)
    nx.draw_networkx(G)
    plt.show()
```

Simple example:

```py
from torchdata.datapipes.iter import FileLister, FileOpener

dp = FileLister()
dp = FileOpener(dp).filter(bool).map(list)

visualize_graph(dp)
```

![sinple](https://user-images.githubusercontent.com/6849766/158603014-6b378534-672d-4016-ad57-0e6de35b07a5.png)

Complex example:

```py
from torchvision.prototype import datasets

dp = datasets.load("coco")

visualize_graph(dp)
```

![coco](https://user-images.githubusercontent.com/6849766/158604303-5fde5b93-a84c-430a-9aee-b6e638a4e56b.png)

---

I've used `networkx` as backend here, but we can use any graph visualization library. Let me know, if I should prettify the plots and send a PR.

**Comment by ejguan** [comment]
Thanks @pmeier , This looks great.
For the backend lib, I personally would prefer tensorboard to visualize the graph because PyTorch is using it to visualize the model graph. https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html#inspect-the-model-using-tensorboard

Code reference from tensorboard about how to transform it into `GraphDef` proto: https://github.com/tensorflow/tensorboard/blob/b2b50a328f9bf6755a72cc6f9fd25bdd792b2bbe/tensorboard/plugins/graph/keras_util.py#L193-L203

**Comment by pmeier** [comment]
One thing that would also simplify debugging, is for each datapipe to have a `__repr__`. We can follow the approach `nn.Module` is going:

```py
class IterDataPipe:
    def extra_repr(self) -> str:
        return ""

    def __repr__(self) -> str:
        return f"{type(self).__name__.replace('IterDataPipe', '')}({self.extra_repr()})"


class MinimalIterDataPipe(IterDataPipe):
    pass


def my_map(x):
    return x


class MapperIterDataPipe(IterDataPipe):
    def __init__(self, fn):
        self.fn = fn

    def extra_repr(self):
        return self.fn.__name__


print(MinimalIterDataPipe())
print(MapperIterDataPipe(my_map))
```

```
Minimal()
Mapper(my_map)
```

That would also improve the graph visualization from #299, since each node could contain the `__repr__` of the datapipe rather than just its name.

**Comment by ejguan** [comment]
> One thing that would also simplify debugging, is for each datapipe to have a `__repr__`. We can follow the approach `nn.Module` is going:

I would like to change it to `iter.ABC` from `ABCIterDataPipe` because the same name can be shared by both `iter` and `map` DataPipe.

**Comment by pmeier** [comment]
Not sure what you mean. Could you give an example? Why does the functional interface need special handling? For example, calling `dp.map(...)` internally simply does `Mapper(dp, ...)`, right? If so, the returned datapipe will have a `__repr__` if `Mapper` has one.

**Comment by pmeier** [comment]
Maybe just color the nodes according to their type? Since it seems this is only relevant for the graph visualization, let's move the discussion to #299 if there is more to it.
