### ISSUE TITLE
[v0.5.0] Release Tracker

### ISSUE THREAD

**Issue by ejguan** [pytorch/data#805]
### 🚀 The feature

We cut a [release branch](https://github.com/pytorch/data/tree/release/0.5) for the 0.5.0 release at the same time with PyTorch.

## Cherry-pick (until TBD)
We will keep cherry-picking all PRs landed to main branch until PyTorch 1.13.0 official released.
When you add PR against release branch, please link the landed PR from main branch.

RC-release can be found in https://download.pytorch.org/whl/test/cpu/torch_test.html or conda: https://anaconda.org/pytorch-test/torchdata

### Motivation, pitch

Tracker for cherry-picking PRs to release branch

**Comment by ejguan** [comment]
Cherry-picking PRs for the week of Oct 3rd:
- [ ] https://github.com/pytorch/data/pull/804

**Comment by ejguan** [comment]
Cherry-picking PRs for the week of Oct 10th:

- [ ] https://github.com/pytorch/data/pull/786
- [ ] https://github.com/pytorch/data/pull/817
- [ ] https://github.com/pytorch/data/pull/818

**Comment by ejguan** [comment]
Cherry-picking PRs for the week of Oct 17th:

**Comment by ejguan** [comment]
Special cherrypick:
We want to cherrypick https://github.com/pytorch/data/pull/810, needs confirmation from torchtext https://github.com/pytorch/text/pull/1942

**Comment by ejguan** [comment]
Backward cherrypick: https://github.com/pytorch/data/pull/853

**Comment by ejguan** [comment]
Cherry-picking PRs for the week of Oct 24th:

- [ ] https://github.com/pytorch/data/pull/858

**Comment by ejguan** [comment]
Closing as 0.5.0 has been released.
